apiVersion: v1
kind: Pod
metadata:
  name: helloworld-static-pod-vol-1
  labels:
    app: helloworld
spec:
  containers:
  - name: hellworld
    image: rackspacetraining/helloworld:1.0
    ports:
    - name: web
      containerPort: 80
    volumeMounts:
      - name: my-nfs
        mountPath: "/mnt/images"
  volumes:
    - name: my-nfs
      nfs:
        server: nfs-server.default.svc.cluster.local
        path: "/exports"
