apiVersion: v1
kind: Pod
metadata:
  name: helloworld-static-pod-2
  labels:
    app: helloworld
spec:
  containers:
    - name: helloworld
      image: rackspacetraining/helloworld:1.0
      ports:
        - name: web
          containerPort: 80
